### ISSUE TITLE
Allow binary artifacts

### ISSUE THREAD

**Issue by atsteffen** [questdb/rust-maven-plugin#17]
btw:_Thanks for taking on this plugin!  I was in the middle of roughing in something similar when I discovered your project._

My use-case involves building various stand-alone binaries which are dispatched and executed on cluster nodes.   Each binary is closely coupled to a java extension which can be plugged into our java application. The java extensions are involved in setting up the command line for the binaries, but does not directly execute them (as you would in JNI). Currently, we build these binaries from a separate repository and merge them with the java code in our CI pipeline.  Since the binaries are closely coupled to java extension code, and tend to change together, managing and building both in a single maven project "sandbox" would simplify our development and CI pipelines.

**Comment by amunra** [comment]
I'd very happily take a PR for this. This is out of scope for us (QuestDB), but it certainly is something that would be good to support.
